### ISSUE TITLE
postcss-custom-properties behavior change with 12.0.3+

### ISSUE THREAD

**Issue by mvsde** [factorial-io/fstack#19]
Starting with postcss-custom-properties v12.0.3, the behavior has changed from including the custom properties as-is in the output bundle to replacing them.

## Minimal reproduction

https://github.com/mvsde/fstack-css-minimal

The folders `postcss-custom-properties@12.0.2` and `postcss-custom-properties@12.0.3` have pinned versions via npm v8.3 overrides (I have no idea if these work with Yarn).

The folder `postcss-custom-properties@latest` has the latest version without overrides (same behavior as 12.0.3).

### postcss-custom-properties@12.0.2

```css
:root {
  --color: hotpink;
}

html {
  color: var(--color);
}

/*# sourceMappingURL=main.css.map */
```

### postcss-custom-properties@12.0.3 / latest

```css
html {
  color: hotpink;
}

/*# sourceMappingURL=main.css.map */
```
